import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="max-w-screen-2xl mx-auto">
      <Head>
        <title>Caleb Rivera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-8 py-20 text-5xl">
        <div>Hi.</div>
        <div>I&apos;m Caleb,</div>
        <div>a Web Developer.</div>
      </div>
    </div>
  );
};

export default Home;
